---
name: calculate PR size

on:
  pull_request:
    branches:
      - main
jobs:
  cal_size:                                                                                            
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: print echo command
        
    
    
      
