---
name: calculate PR size

on:
  workflow_dispatch:
  # pull_request:
  #   branches:
  #     - main
jobs:
  cal_size:                                                                                            
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: print echo command
        run: echo "{{ github.event.pull_request.head}}"
        
    
    
      
